export const PRAKRITI_QUESTIONS = [
  {
    category: "Body Frame",
    question: "How would you describe your body frame and weight?",
    options: [
      { text: "Very tall or very short, with a thin frame that struggles to gain weight.", dosha: "vata" },
      { text: "Light, slender build with prominent, sometimes cracking, joints.", dosha: "vata" },
      { text: "Medium, athletic build that gains or loses muscle easily.", dosha: "pitta" },
      { text: "Well-proportioned frame with good muscle definition.", dosha: "pitta" },
      { text: "Broad, sturdy frame with a tendency to gain weight easily.", dosha: "kapha" },
      { text: "Large, well-developed body that feels solid and heavy.", dosha: "kapha" },
    ],
  },
  {
    category: "Skin Type",
    question: "What is your skin usually like?",
    options: [
      { text: "Skin is often dry, rough, and may have a dull complexion.", dosha: "vata" },
      { text: "Thin skin that is cool to the touch and prone to chapping.", dosha: "vata" },
      { text: "Fair, sensitive skin that flushes easily and is prone to moles or freckles.", dosha: "pitta" },
      { text: "Oily in the T-zone, prone to acne, breakouts, or inflammatory rashes.", dosha: "pitta" },
      { text: "Thick, smooth, and oily skin that is often pale and cool.", dosha: "kapha" },
      { text: "Moist, soft skin with a lustrous complexion and minimal wrinkles.", dosha: "kapha" },
    ],
  },
  {
    category: "Hair",
    question: "Describe your hair.",
    options: [
      { text: "Hair is thin, dry, and can be frizzy or brittle.", dosha: "vata" },
      { text: "Often have split ends and a tendency towards dandruff.", dosha: "vata" },
      { text: "Fine, soft, straight hair, prone to premature graying or thinning.", dosha: "pitta" },
      { text: "Oily scalp with hair that is naturally reddish or blonde.", dosha: "pitta" },
      { text: "Thick, lustrous, and wavy hair.", dosha: "kapha" },
      { text: "Abundant, strong, and oily hair that is typically dark.", dosha: "kapha" },
    ],
  },
  {
    category: "Appetite",
    question: "How is your appetite?",
    options: [
      { text: "Variable and unpredictable; I can be hungry one moment and not the next.", dosha: "vata" },
      { text: "I often forget to eat or feel full with small amounts of food.", dosha: "vata" },
      { text: "Strong and sharp; I feel intense hunger and get irritable if a meal is delayed.", dosha: "pitta" },
      { text: "I can eat large meals and feel hungry again within a few hours.", dosha: "pitta" },
      { text: "Steady and consistent, but not overpowering. I enjoy my food.", dosha: "kapha" },
      { text: "I can easily skip meals without discomfort, but have a tendency for emotional eating.", dosha: "kapha" },
    ],
  },
  {
    category: "Digestion",
    question: "How would you describe your digestion?",
    options: [
      { text: "Irregular, often experiencing gas, bloating, or constipation.", dosha: "vata" },
      { text: "Sensitive digestion that is easily disturbed by routine changes.", dosha: "vata" },
      { text: "Fast and strong; I rarely feel heavy after eating.", dosha: "pitta" },
      { text: "Prone to acidity, heartburn, or loose stools when imbalanced.", dosha: "pitta" },
      { text: "Slow and heavy; I often feel full for a long time after meals.", dosha: "kapha" },
      { text: "My digestion is generally regular but can become sluggish.", dosha: "kapha" },
    ],
  },
  {
    category: "Climate Preference",
    question: "What climate do you feel most comfortable in?",
    options: [
      { text: "I strongly dislike cold and windy weather and crave warmth.", dosha: "vata" },
      { text: "I thrive in warm, humid, and sunny environments.", dosha: "vata" },
      { text: "I strongly dislike intense heat and direct sun.", dosha: "pitta" },
      { text: "I feel best in cool, well-ventilated places and prefer winter over summer.", dosha: "pitta" },
      { text: "I am uncomfortable in damp, cold, and cloudy weather.", dosha: "kapha" },
      { text: "I enjoy warm and dry climates and can tolerate a range of temperatures.", dosha: "kapha" },
    ],
  },
  {
    category: "Temperament",
    question: "How is your general temperament?",
    options: [
      { text: "Enthusiastic, lively, and full of creative ideas.", dosha: "vata" },
      { text: "Quick-thinking and adaptable, but can also be indecisive.", dosha: "vata" },
      { text: "Intelligent, sharp, and highly focused on goals.", dosha: "pitta" },
      { text: "Articulate and direct, but can be critical or short-tempered.", dosha: "pitta" },
      { text: "Calm, steady, and generally easy-going.", dosha: "kapha" },
      { text: "Methodical, patient, and sometimes resistant to change.", dosha: "kapha" },
    ],
  },
  {
    category: "Response to Stress",
    question: "How do you typically react to stress?",
    options: [
      { text: "I become anxious, worried, and my mind starts racing.", dosha: "vata" },
      { text: "I feel overwhelmed, scattered, and have trouble sleeping.", dosha: "vata" },
      { text: "I become irritable, impatient, and may get into arguments.", dosha: "pitta" },
      { text: "I feel frustrated, angry, and want to take immediate action.", dosha: "pitta" },
      { text: "I tend to withdraw, become quiet, and avoid confrontation.", dosha: "kapha" },
      { text: "I might oversleep, feel lethargic, or turn to food for comfort.", dosha: "kapha" },
    ],
  },
  {
    category: "Sleep Pattern",
    question: "What is your sleep pattern like?",
    options: [
      { text: "I am a light sleeper and easily woken. My sleep can be irregular.", dosha: "vata" },
      { text: "I often have vivid dreams and may talk or grind my teeth in my sleep.", dosha: "vata" },
      { text: "I am a moderately deep sleeper but can wake up feeling hot.", dosha: "pitta" },
      { text: "I fall asleep easily and sleep soundly, but for shorter durations (6-7 hours).", dosha: "pitta" },
      { text: "I am a very deep, heavy sleeper and can sleep for long hours.", dosha: "kapha" },
      { text: "I find it difficult to wake up in the morning and often feel groggy.", dosha: "kapha" },
    ],
  },
  {
    category: "Energy Levels",
    question: "How are your energy levels throughout the day?",
    options: [
      { text: "My energy comes in short bursts; I can be very active then suddenly crash.", dosha: "vata" },
      { text: "My stamina is variable and I tire easily.", dosha: "vata" },
      { text: "I have strong, focused energy and a drive to be productive.", dosha: "pitta" },
      { text: "My energy is consistent, but I can push myself to the point of burnout.", dosha: "pitta" },
      { text: "I have great stamina and consistent energy once I get going.", dosha: "kapha" },
      { text: "I am slow to start, but my energy is steady and endures for a long time.", dosha: "kapha" },
    ],
  },
  {
    category: "Mind & Memory",
    question: "How would you describe your memory and learning style?",
    options: [
      { text: "I learn quickly but also forget quickly. My long-term memory is spotty.", dosha: "vata" },
      { text: "I'm a fast learner with a creative mind, but I can be easily distracted.", dosha: "vata" },
      { text: "I have a sharp, penetrating memory and learn systematically.", dosha: "pitta" },
      { text: "I grasp concepts quickly and have a good medium-term memory.", dosha: "pitta" },
      { text: "I learn slowly but have an excellent long-term memory; I never forget.", dosha: "kapha" },
      { text: "My mind is methodical, and I retain information well once learned.", dosha: "kapha" },
    ],
  },
  {
    category: "Emotions",
    question: "Which set of emotions best describes your general state?",
    options: [
      { text: "Enthusiasm, joy, and creativity, but also anxiety and fear when imbalanced.", dosha: "vata" },
      { text: "My moods change quickly and are often unpredictable.", dosha: "vata" },
      { text: "Courage, confidence, and ambition, but also anger and jealousy when imbalanced.", dosha: "pitta" },
      { text: "I am passionate and have strong feelings, both positive and negative.", dosha: "pitta" },
      { text: "Calmness, compassion, and contentment, but also attachment and greed when imbalanced.", dosha: "kapha" },
      { text: "I am emotionally steady and not easily upset.", dosha: "kapha" },
    ],
  },
  {
    category: "Physical Activity",
    question: "What is your approach to physical activity?",
    options: [
      { text: "I enjoy fast-paced, stimulating activities like dancing or running, but in short bursts.", dosha: "vata" },
      { text: "I have bursts of energy but can run out of steam quickly.", dosha: "vata" },
      { text: "I am competitive and enjoy challenging, intense workouts.", dosha: "pitta" },
      { text: "I have good endurance and enjoy activities that build strength and skill.", dosha: "pitta" },
      { text: "I prefer gentle, endurance-based activities like walking or swimming.", dosha: "kapha" },
      { text: "I am slow to get started but have excellent stamina once I do.", dosha: "kapha" },
    ],
  },
  {
    category: "Speech Pattern",
    question: "How do you typically speak?",
    options: [
      { text: "I speak quickly, am very talkative, and may jump from topic to topic.", dosha: "vata" },
      { text: "My voice can be high-pitched and I sometimes talk with my hands.", dosha: "vata" },
      { text: "I speak clearly, articulately, and with a convincing tone.", dosha: "pitta" },
      { text: "My speech is sharp and precise, and I can be persuasive or argumentative.", dosha: "pitta" },
      { text: "I speak slowly, in a measured and calm tone.", dosha: "kapha" },
      { text: "My voice is pleasant and melodic, but I may not speak much.", dosha: "kapha" },
    ],
  },
  {
    category: "Eyes",
    question: "Describe your eyes.",
    options: [
      { text: "Small, active, and may be dull or dry. Prone to twitching.", dosha: "vata" },
      { text: "My eyes dart around and I have thin eyelashes.", dosha: "vata" },
      { text: "Medium-sized, sharp, and penetrating gaze. Can be sensitive to light.", dosha: "pitta" },
      { text: "Eyes are often light-colored (hazel, green) and can get red or bloodshot.", dosha: "pitta" },
      { text: "Large, calm, and attractive eyes with thick lashes.", dosha: "kapha" },
      { text: "My eyes are prominent, white, and have a loving expression.", dosha: "kapha" },
    ],
  },
  {
    category: "Nails",
    question: "What are your fingernails like?",
    options: [
      { text: "Dry, brittle, and rough. They break easily.", dosha: "vata" },
      { text: "Nails are often ridged and I have a habit of biting them.", dosha: "vata" },
      { text: "Soft, flexible, and pink with a slight luster.", dosha: "pitta" },
      { text: "Nails are medium-sized and have a well-defined shape.", dosha: "pitta" },
      { text: "Thick, strong, and smooth with a nice shine.", dosha: "kapha" },
      { text: "Nails are large, pale, and grow evenly.", dosha: "kapha" },
    ],
  },
  {
    category: "Thirst",
    question: "How would you describe your level of thirst?",
    options: [
      { text: "My thirst is variable; sometimes I'm very thirsty, other times I forget to drink.", dosha: "vata" },
      { text: "I tend to be dehydrated easily.", dosha: "vata" },
      { text: "I have a strong thirst and drink a lot of water.", dosha: "pitta" },
      { text: "I prefer cool drinks and feel uncomfortable without regular fluid intake.", dosha: "pitta" },
      { text: "My thirst is generally low; I can go for long periods without drinking.", dosha: "kapha" },
      { text: "I rarely feel intensely thirsty.", dosha: "kapha" },
    ],
  },
  {
    category: "Sweating",
    question: "How much do you typically sweat?",
    options: [
      { text: "I sweat very little, even in hot weather or during exercise.", dosha: "vata" },
      { text: "My sweat is minimal and has little odor.", dosha: "vata" },
      { text: "I sweat easily and profusely, especially when it's hot.", dosha: "pitta" },
      { text: "My sweat can have a strong, sharp odor.", dosha: "pitta" },
      { text: "I sweat moderately, but it's consistent during exertion.", dosha: "kapha" },
      { text: "My sweat is cool and pleasant-smelling.", dosha: "kapha" },
    ],
  },
  {
    category: "Joints",
    question: "How are your joints?",
    options: [
      { text: "My joints are prominent, thin, and make cracking or popping sounds.", dosha: "vata" },
      { text: "They can be stiff and achy, especially in cold weather.", dosha: "vata" },
      { text: "My joints are loose and flexible.", dosha: "pitta" },
      { text: "I rarely have joint issues, but can be prone to inflammation if overworked.", dosha: "pitta" },
      { text: "My joints are large, well-lubricated, and very stable.", dosha: "kapha" },
      { text: "They are strong and sturdy, but can feel stiff if I'm inactive.", dosha: "kapha" },
    ],
  },
  {
    category: "Dreams",
    question: "What are your dreams usually like?",
    options: [
      { text: "I have active, vivid, and often anxious dreams of flying, running, or being chased.", dosha: "vata" },
      { text: "I dream frequently but often don't remember them well.", dosha: "vata" },
      { text: "My dreams are colorful, intense, and can be about conflict, problem-solving, or fire.", dosha: "pitta" },
      { text: "I have passionate, focused dreams and usually remember them clearly.", dosha: "pitta" },
      { text: "My dreams are calm, romantic, and often involve water, clouds, or nature.", dosha: "kapha" },
      { text: "I don't dream very often, or my dreams are simple and peaceful.", dosha: "kapha" },
    ],
  },
];
